// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuya.Infrastructure;

#nullable disable

namespace Tuya.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tuya.Domain.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Carrera 1",
                            CellPhone = "3009991234",
                            Email = "Carlos@test.com",
                            Name = "Carlos Andres Perez"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Carrera 50",
                            CellPhone = "3019873216",
                            Email = "Maria@test.com",
                            Name = "Maria Camila Zuluaga"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Avenida 10",
                            CellPhone = "3504445465",
                            Email = "Daniela@test.com",
                            Name = "Daniela Castro"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Calle 44",
                            CellPhone = "3019513548",
                            Email = "Juan@test.com",
                            Name = "Juan Camilo Munera"
                        });
                });

            modelBuilder.Entity("Tuya.Domain.Entities.OrderDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("Tuya.Domain.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Tuya.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "AAA",
                            Name = "Café",
                            UnitPrice = 25000m
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "BBB",
                            Name = "Arroz Premium",
                            UnitPrice = 6000m
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            Description = "CCC",
                            Name = "Lentejas",
                            UnitPrice = 4000m
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "DDD",
                            Name = "Frijoles",
                            UnitPrice = 4500m
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            Description = "EEE",
                            Name = "Arroz",
                            UnitPrice = 3500m
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "FFF",
                            Name = "Salsa de tomate",
                            UnitPrice = 13000m
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "GGG",
                            Name = "Mostaza",
                            UnitPrice = 8000m
                        });
                });

            modelBuilder.Entity("Tuya.Domain.Entities.OrderDetailEntity", b =>
                {
                    b.HasOne("Tuya.Domain.Entities.OrderEntity", "OrderEntity")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuya.Domain.Entities.ProductEntity", "ProductEntity")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderEntity");

                    b.Navigation("ProductEntity");
                });

            modelBuilder.Entity("Tuya.Domain.Entities.OrderEntity", b =>
                {
                    b.HasOne("Tuya.Domain.Entities.CustomerEntity", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("IdCustomer")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Tuya.Domain.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Tuya.Domain.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Tuya.Domain.Entities.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
